<a href="https://colab.research.google.com/github/saurater/TensorFlow-Developer-Certificate/blob/main/C4_W2_Lab_1_features_and_labels_V2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
dataset =  tf.data.Dataset.range(10)

In [8]:
for val in dataset:
  print(val.numpy())

0
1
2
3
4
5
6
7
8
9


In [9]:
dataset = tf.data.Dataset.range(10)

In [11]:
dataset = dataset.window(size=5,shift = 1)

In [12]:
for window_dataset in dataset:
  print(window_dataset)

<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>


In [14]:
for window_dataset in dataset:
  print([item.numpy() for item in window_dataset])

[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]
[6, 7, 8, 9]
[7, 8, 9]
[8, 9]
[9]


In [22]:
dataset =  tf.data.Dataset.range(10)

dataset =  dataset.window(size = 5, shift =1, drop_remainder = True)

for window_dataset in dataset:
  print([item.numpy() for item in window_dataset])

[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]


In [24]:
type(dataset)

tensorflow.python.data.ops.dataset_ops.WindowDataset

In [50]:
dataset = tf.data.Dataset.range(10)

dataset = dataset.window(size =5, shift =1, drop_remainder = True)

dataset = dataset.flat_map(lambda window : window.batch(5))

In [51]:
for window_dataset in dataset:
  print([item.numpy() for item in window_dataset])

[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]


In [52]:
dataset = dataset.map(lambda window: (window[:-1], window[-1]))

In [53]:
for x,y in dataset:
  print("x = ", x.numpy())
  print("y = ", y.numpy())
  print()

x =  [0 1 2 3]
y =  4

x =  [1 2 3 4]
y =  5

x =  [2 3 4 5]
y =  6

x =  [3 4 5 6]
y =  7

x =  [4 5 6 7]
y =  8

x =  [5 6 7 8]
y =  9



In [69]:
dataset =  tf.data.Dataset.range(10)

dataset = dataset.window(size = 5, shift =1, drop_remainder = True)

dataset = dataset.flat_map(lambda window : window.batch(5))

dataset = dataset.map(lambda window : (window[:-1], window[-1] ))

dataset =  dataset.shuffle(buffer_size = 10)

for x,y in dataset:
  print("x = ", x.numpy())
  print("y = ", y.numpy())
  print()


x =  [5 6 7 8]
y =  9

x =  [0 1 2 3]
y =  4

x =  [3 4 5 6]
y =  7

x =  [1 2 3 4]
y =  5

x =  [4 5 6 7]
y =  8

x =  [2 3 4 5]
y =  6



In [78]:
dataset =  tf.data.Dataset.range(10)

dataset = dataset.window(size = 5, shift =1, drop_remainder = True)

dataset =  dataset.flat_map(lambda window : window.batch(5))

dataset = dataset.map(lambda window : (window[:-1], window[-1]))

datset = dataset.shuffle(buffer_size=10)

dataset = datset.batch(2).prefetch(1)

for x,y in dataset:
  print("x = ", x.numpy())
  print("y = ", y.numpy())
  print()

x =  [[3 4 5 6]
 [1 2 3 4]]
y =  [7 5]

x =  [[0 1 2 3]
 [5 6 7 8]]
y =  [4 9]

x =  [[4 5 6 7]
 [2 3 4 5]]
y =  [8 6]

